apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-hpa
 labels:
   app: nginx
spec:
 replicas: 1
 selector:
   matchLabels:
     app: nginx-hpa
 template:
   metadata:
     labels:
       app: nginx-hpa
   spec:
     containers:
     - name: nginx-cont
       image: nginx:1.12
       ports:
       - containerPort: 80
       resources:
         limits:
           cpu: 300m
           memory: 200Mi
         requests:
           cpu: 150m
           memory: 100Mi

