apiVersion: apps/v1
kind: Deployment
metadata:
 name: nginx-deployment
 labels:
   app: nginx
   env: dev2
spec:
 replicas: 2
 selector:
   matchLabels:
     app: nginx
     env: dev
 template:
   metadata:
     labels:
       app: nginx
       env: dev
   spec:
     containers:
     - name: nginx
       image: nginx:1.12
       ports:
       - containerPort: 80

